image mc idle = "images/mc_placeholder.png"
image mc thinking = "images/mc_placeholder.png"
image mc shocked = "images/mc_placeholder.png"
image mc panicked = "images/mc_placeholder.png"
image mc celebrate = "images/mc_placeholder.png"
image mc running = "images/mc_placeholder.png"
image mc typing = "images/mc_placeholder.png"
image mc hiding = "images/mc_placeholder.png"
